-- Generated from seed-places.json by scripts/build-seed-sql.mjs; edit the JSON, not this file.
-- Starting catalog: Trimaco's warehouse, major hospitals and cities. Safe to run again.
insert into public.places (name, aliases, region, kind, city, address) values
  ('מחסן נס ציונה', array['מחסן', 'המחסן', 'מפעל', 'המפעל', 'משרד', 'המשרד', 'טרימקו', 'הזמנות']::text[], 'center', 'depot', 'נס ציונה', 'אילן רמון 5, נס ציונה'),
  ('איכילוב', array['סוראסקי', 'תל אביב סוראסקי', 'איכלוב']::text[], 'tlv', 'hospital', 'תל אביב', null),
  ('שיבא', array['תל השומר', 'שיבא תל השומר', 'שיבה']::text[], 'tlv', 'hospital', 'רמת גן', null),
  ('וולפסון', array['וולפסון חולון', 'ולפסון']::text[], 'tlv', 'hospital', 'חולון', null),
  ('מעייני הישועה', array['מעיני הישועה']::text[], 'tlv', 'hospital', 'בני ברק', null),
  ('אסותא רמת החייל', array['אסותא ת"א', 'אסותא תל אביב', 'אסותא רמת החיל']::text[], 'tlv', 'hospital', 'תל אביב', null),
  ('רפאל', array['בית חולים רפאל']::text[], 'tlv', 'hospital', 'תל אביב', null),
  ('בילינסון', array['בלינסון', 'רבין', 'רבין בילינסון']::text[], 'center', 'hospital', 'פתח תקווה', null),
  ('השרון', array['בית חולים השרון', 'רבין השרון']::text[], 'center', 'hospital', 'פתח תקווה', null),
  ('שניידר', array[]::text[], 'center', 'hospital', 'פתח תקווה', null),
  ('אסותא ראשון לציון', array['אסותא ראשון', 'אסותא ראשל"צ']::text[], 'center', 'hospital', 'ראשון לציון', null),
  ('שמיר (אסף הרופא)', array['אסף הרופא', 'שמיר', 'שמיר אסף הרופא']::text[], 'center', 'hospital', 'באר יעקב', null),
  ('קפלן', array['מרכז רפואי קפלן']::text[], 'center', 'hospital', 'רחובות', null),
  ('הרצליה מדיקל סנטר', array['הרצליה מדיקל', 'מדיקל הרצליה']::text[], 'sharon', 'hospital', 'הרצליה', null),
  ('מאיר', array['מאיר כפר סבא']::text[], 'sharon', 'hospital', 'כפר סבא', null),
  ('לניאדו', array[]::text[], 'sharon', 'hospital', 'נתניה', null),
  ('הלל יפה', array['הילל יפה']::text[], 'sharon', 'hospital', 'חדרה', null),
  ('הדסה עין כרם', array['הדסה', 'עין כרם']::text[], 'jerusalem', 'hospital', 'ירושלים', null),
  ('הדסה הר הצופים', array['הר הצופים']::text[], 'jerusalem', 'hospital', 'ירושלים', null),
  ('שערי צדק', array[]::text[], 'jerusalem', 'hospital', 'ירושלים', null),
  ('אסותא אשדוד', array['סמסון אסותא']::text[], 'south', 'hospital', 'אשדוד', null),
  ('אסותא באר שבע', array['אסותא ב"ש']::text[], 'south', 'hospital', 'באר שבע', null),
  ('סורוקה', array[]::text[], 'south', 'hospital', 'באר שבע', null),
  ('ברזילי', array['ברזילי אשקלון', 'ברזילאי']::text[], 'south', 'hospital', 'אשקלון', null),
  ('יוספטל', array[]::text[], 'south', 'hospital', 'אילת', null),
  ('רמב"ם', array[]::text[], 'north', 'hospital', 'חיפה', null),
  ('כרמל', array[]::text[], 'north', 'hospital', 'חיפה', null),
  ('בני ציון', array[]::text[], 'north', 'hospital', 'חיפה', null),
  ('אסותא חיפה', array[]::text[], 'north', 'hospital', 'חיפה', null),
  ('אלישע', array[]::text[], 'north', 'hospital', 'חיפה', null),
  ('הגליל', array['המרכז הרפואי לגליל', 'הגליל נהריה']::text[], 'north', 'hospital', 'נהריה', null),
  ('פוריה', array[]::text[], 'north', 'hospital', 'טבריה', null),
  ('העמק', array[]::text[], 'north', 'hospital', 'עפולה', null),
  ('זיו', array[]::text[], 'north', 'hospital', 'צפת', null),
  ('סנט ג''וזף', array['סנט גוזף', 'סנט ג׳וזף', 'סנט יוסף']::text[], 'jerusalem', 'hospital', 'ירושלים', null),
  ('הצרפתי נצרת', array['נצרת צרפתי', 'בית החולים הצרפתי']::text[], 'north', 'hospital', 'נצרת', null),
  ('האנגלי נצרת', array['נצרת אנגלי', 'בית החולים האנגלי']::text[], 'north', 'hospital', 'נצרת', null),
  ('לוינשטיין', array['בית לוינשטיין', 'לוינשטין']::text[], 'sharon', 'hospital', 'רעננה', null),
  ('אוניברסיטת תל אביב', array['אוניברסיטת ת"א']::text[], 'tlv', 'other', 'תל אביב', null),
  ('הקריה האקדמית אונו', array['קריה האקדמית אונו', 'הקריה האקדמית']::text[], 'center', 'other', 'קריית אונו', null),
  ('תל אביב', array['ת"א', 'תל-אביב', 'יפו', 'תל אביב יפו']::text[], 'tlv', 'city', null, null),
  ('רמת גן', array['ר"ג']::text[], 'tlv', 'city', null, null),
  ('גבעתיים', array[]::text[], 'tlv', 'city', null, null),
  ('חולון', array[]::text[], 'tlv', 'city', null, null),
  ('בת ים', array[]::text[], 'tlv', 'city', null, null),
  ('בני ברק', array['ב"ב']::text[], 'tlv', 'city', null, null),
  ('פתח תקווה', array['פ"ת', 'פתח תקוה']::text[], 'center', 'city', null, null),
  ('ראש העין', array[]::text[], 'center', 'city', null, null),
  ('ראשון לציון', array['ראשל"צ', 'ראשון']::text[], 'center', 'city', null, null),
  ('רחובות', array[]::text[], 'center', 'city', null, null),
  ('נס ציונה', array[]::text[], 'center', 'city', null, null),
  ('יבנה', array[]::text[], 'center', 'city', null, null),
  ('לוד', array[]::text[], 'center', 'city', null, null),
  ('רמלה', array[]::text[], 'center', 'city', null, null),
  ('מודיעין', array['מודיעין מכבים רעות']::text[], 'center', 'city', null, null),
  ('שוהם', array[]::text[], 'center', 'city', null, null),
  ('בית עריף', array[]::text[], 'center', 'city', null, null),
  ('יהוד', array['יהוד מונוסון']::text[], 'center', 'city', null, null),
  ('אור יהודה', array[]::text[], 'center', 'city', null, null),
  ('קריית אונו', array['קרית אונו']::text[], 'center', 'city', null, null),
  ('גדרה', array[]::text[], 'center', 'city', null, null),
  ('באר יעקב', array[]::text[], 'center', 'city', null, null),
  ('אלעד', array[]::text[], 'center', 'city', null, null),
  ('גני תקווה', array[]::text[], 'center', 'city', null, null),
  ('סביון', array[]::text[], 'center', 'city', null, null),
  ('מזכרת בתיה', array[]::text[], 'center', 'city', null, null),
  ('קריית עקרון', array['קרית עקרון']::text[], 'center', 'city', null, null),
  ('הרצליה', array[]::text[], 'sharon', 'city', null, null),
  ('רעננה', array[]::text[], 'sharon', 'city', null, null),
  ('כפר סבא', array[]::text[], 'sharon', 'city', null, null),
  ('הוד השרון', array[]::text[], 'sharon', 'city', null, null),
  ('רמת השרון', array[]::text[], 'sharon', 'city', null, null),
  ('נתניה', array[]::text[], 'sharon', 'city', null, null),
  ('חדרה', array[]::text[], 'sharon', 'city', null, null),
  ('כפר יונה', array[]::text[], 'sharon', 'city', null, null),
  ('אבן יהודה', array[]::text[], 'sharon', 'city', null, null),
  ('קדימה צורן', array['קדימה']::text[], 'sharon', 'city', null, null),
  ('פרדס חנה כרכור', array['פרדס חנה']::text[], 'sharon', 'city', null, null),
  ('קיסריה', array[]::text[], 'sharon', 'city', null, null),
  ('ירושלים', array[]::text[], 'jerusalem', 'city', null, null),
  ('בית שמש', array[]::text[], 'jerusalem', 'city', null, null),
  ('מבשרת ציון', array['מבשרת']::text[], 'jerusalem', 'city', null, null),
  ('מעלה אדומים', array[]::text[], 'jerusalem', 'city', null, null),
  ('אשדוד', array[]::text[], 'south', 'city', null, null),
  ('אשקלון', array[]::text[], 'south', 'city', null, null),
  ('באר שבע', array['ב"ש']::text[], 'south', 'city', null, null),
  ('קריית גת', array['קרית גת']::text[], 'south', 'city', null, null),
  ('קריית מלאכי', array['קרית מלאכי']::text[], 'south', 'city', null, null),
  ('שדרות', array[]::text[], 'south', 'city', null, null),
  ('נתיבות', array[]::text[], 'south', 'city', null, null),
  ('אופקים', array[]::text[], 'south', 'city', null, null),
  ('דימונה', array[]::text[], 'south', 'city', null, null),
  ('ערד', array[]::text[], 'south', 'city', null, null),
  ('אילת', array[]::text[], 'south', 'city', null, null),
  ('חיפה', array[]::text[], 'north', 'city', null, null),
  ('קריית ביאליק', array['קרית ביאליק']::text[], 'north', 'city', null, null),
  ('קריית מוצקין', array['קרית מוצקין']::text[], 'north', 'city', null, null),
  ('קריית אתא', array['קרית אתא']::text[], 'north', 'city', null, null),
  ('קריית ים', array['קרית ים']::text[], 'north', 'city', null, null),
  ('טירת כרמל', array[]::text[], 'north', 'city', null, null),
  ('נשר', array[]::text[], 'north', 'city', null, null),
  ('עכו', array[]::text[], 'north', 'city', null, null),
  ('נהריה', array[]::text[], 'north', 'city', null, null),
  ('כרמיאל', array[]::text[], 'north', 'city', null, null),
  ('עפולה', array[]::text[], 'north', 'city', null, null),
  ('טבריה', array[]::text[], 'north', 'city', null, null),
  ('צפת', array[]::text[], 'north', 'city', null, null),
  ('נצרת', array[]::text[], 'north', 'city', null, null),
  ('נוף הגליל', array['נצרת עילית']::text[], 'north', 'city', null, null),
  ('יוקנעם', array['יקנעם']::text[], 'north', 'city', null, null),
  ('זכרון יעקב', array[]::text[], 'north', 'city', null, null),
  ('קריית שמונה', array['קרית שמונה']::text[], 'north', 'city', null, null),
  ('מגדל העמק', array[]::text[], 'north', 'city', null, null),
  ('בית שאן', array[]::text[], 'north', 'city', null, null),
  ('רמת אביב', array[]::text[], 'tlv', 'city', null, null),
  ('קיבוץ גזר', array['גזר']::text[], 'center', 'city', null, null),
  ('קיבוץ אייל', array[]::text[], 'sharon', 'city', null, null),
  ('גן חיים', array[]::text[], 'sharon', 'city', null, null),
  ('גני עם', array[]::text[], 'sharon', 'city', null, null),
  ('טייבה', array['טיבה']::text[], 'sharon', 'city', null, null),
  ('כפר הס', array[]::text[], 'sharon', 'city', null, null),
  ('רמות השבים', array[]::text[], 'sharon', 'city', null, null),
  ('קרני שומרון', array[]::text[], 'sharon', 'city', null, null),
  ('סלעית', array[]::text[], 'sharon', 'city', null, null),
  ('בנימינה', array[]::text[], 'sharon', 'city', null, null),
  ('להבים', array[]::text[], 'south', 'city', null, null),
  ('רהט', array[]::text[], 'south', 'city', null, null),
  ('רמת ישי', array[]::text[], 'north', 'city', null, null),
  ('קריית טבעון', array['קרית טבעון', 'טבעון']::text[], 'north', 'city', null, null),
  ('דלית אל כרמל', array['דאלית אל כרמל']::text[], 'north', 'city', null, null),
  ('שפרעם', array[]::text[], 'north', 'city', null, null),
  ('קצרין', array[]::text[], 'north', 'city', null, null),
  ('מרום גולן', array[]::text[], 'north', 'city', null, null),
  ('בני יהודה', array['ישוב בני יהודה']::text[], 'north', 'city', null, null),
  ('עמק הירדן', array[]::text[], 'north', 'city', null, null),
  ('מבואות החרמון', array[]::text[], 'north', 'city', null, null)
on conflict (name) do nothing;
